=== smGnd/Uczelnia/sem4/xml/lab3/zad3.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT	automat		(stany, alfabet, funkcja, spocz, skon)>
<!ATTLIST	automat
					typ 		(deterministyczny|niedeterministyczny) #REQUIRED>
<!ELEMENT	stany	(stan)+>
<!ELEMENT	stan		(#PCDATA)>
<!ELEMENT	alfabet		(symbol+)>
<!ELEMENT	symbol		(#PCDATA)>
<!ELEMENT	funkcja		(przejscie+)>
<!ELEMENT	przejscie	(#PCDATA)>
<!ATTLIST	przejscie
					stan		CDATA #REQUIRED
					symbol		CDATA #REQUIRED
					nstan		CDATA #REQUIRED>

<!ELEMENT	spocz		(#PCDATA)>
<!ELEMENT	skon		(stankon+)>
<!ELEMENT	stankon		(#PCDATA)>

=== smGnd/Uczelnia/sem4/xml/lab3/zad3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE automat SYSTEM "zad3.dtd">

<automat typ="deterministyczny">
	<stany>
		<stan>q0</stan>
		<stan>q1</stan>
		<stan>q2</stan>
	</stany>
	<alfabet>
		<symbol>a</symbol>
		<symbol>b</symbol>
	</alfabet>
	<funkcja>
		<przejscie stan="q0" symbol="a" nstan="q0" />
		<przejscie stan="q0" symbol="b" nstan="q1" />
		<przejscie stan
	</funkcja>
</automat>
