=== smGnd/Uczelnia/sem4/xml/lab7/zad2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="wypozyczalnia">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="kaseta" type="kaseta" maxOccurs="unbounded"/>
				<xsd:element name="wypozyczenie" type="wypozyczenie" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:key name="kl-kod">
			<xsd:selector xpath="kaseta" />
			<xsd:field xpath="@kasetaid" />
		</xsd:key>
	
		<xsd:unique name="kl-tytulkod">
			<xsd:selector xpath="kaseta" />
			<xsd:field xpath="tytul" />
			<xsd:field xpath="@kasetaid" />
		</xsd:unique>
	
		<xsd:key name="kl-wyp">
			<xsd:selector xpath="wypozyczenie" />
			<xsd:field xpath="@wypid" />
		</xsd:key>
	
		<xsd:keyref name="wyp-kaseta" refer="kl-kod">
			<xsd:selector xpath="wypozyczenie" />
			<xsd:field xpath="film" />
		</xsd:keyref>
		
	</xsd:element>
	
	<xsd:complexType name="kaseta">
		<xsd:sequence>
			<xsd:element name="tytul" type="xsd:string" />
			<xsd:element name="cena" type="cena" />
			<xsd:element name="rok" type="rok" />
			<xsd:element name="rezyser" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="kasetaid" type="kod" />
	</xsd:complexType>
	
	<xsd:simpleType name="cena">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]*,[0-9]{2}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="rok">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(19|20)[0-9]{2}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="wypozyczenie">
		<xsd:sequence>
			<xsd:element name="datapocz" type="data" />
			<xsd:element name="datakon" type="data" />
			<xsd:element name="film" type="kod" />
		</xsd:sequence>
		<xsd:attribute name="wypid" type="kod" />
	</xsd:complexType>
	
	<xsd:simpleType name="data">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="kod">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z]{3}-[0-9]{5}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	
</xsd:schema>

=== smGnd/Uczelnia/sem4/xml/lab7/zad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<wypozyczalnia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zad2.xsd">
	<kaseta kasetaid="SWL-88590">
		<tytul>Gwiezdne Wojny</tytul>
		<cena>15,00</cena>
		<rok>1978</rok>
		<rezyser>G.Lucas</rezyser>
	</kaseta>
	<kaseta kasetaid="KZP-12421">
		<tytul>Krzesło z pozytywką</tytul>
		<cena>2,00</cena>
		<rok>1995</rok>
		<rezyser>A.Niemrawy</rezyser>
	</kaseta>
	<kaseta kasetaid="FTM-55302">
		<tytul>Film</tytul>
		<cena>5,00</cena>
		<rok>1928</rok>
		<rezyser>B.Mosse</rezyser>
	</kaseta>
	<kaseta kasetaid="HZJ-12345">
		<tytul>Historia z jedynką</tytul>
		<cena>12,50</cena>
		<rok>1999</rok>
		<rezyser>A.Zonk</rezyser>
	</kaseta>
	<wypozyczenie wypid="WSW-17210">
		<datapocz>17-02-2010</datapocz>
		<datakon>27-02-2010</datakon>
		<film>SWL-88590</film>
	</wypozyczenie>
	<wypozyczenie wypid="WFT-22412">
		<datapocz>22-04-2012</datapocz>
		<datakon>01-05-2012</datakon>
		<film>KZL-12421</film>
	</wypozyczenie>
</wypozyczalnia>
